### ISSUE TITLE
Error with theano v0.9.0

### ISSUE THREAD

**Issue by deepali-c** [uoguelph-mlrg/theano_alexnet#29]
I observed the following error while executing alexnet with theano v0.9.0:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "train.py", line 54, in train_net
    model = AlexNet(config)
  File "<pathto>/alexnet-theano/alex_net.py", line 130, in __init__
    self.errors_top_5 = softmax_layer8.errors_top_x(y, 5)
  File "./lib/layers.py", line 312, in errors_top_x
    return T.mean(T.min(T.neq(y_pred_top_x, y_top_x), axis=1))
  File "<pathto>/site-packages/theano/tensor/basic.py", line 1742, in min
    raise NotImplementedError()
NotImplementedError
```

**Comment by hma02** [comment]
@deepali-c This error is because the output of `T.neq` is not of `int8` type when switching to theano0.9.0.

See this commit: db33b0fe708c26
Should be fixed now.

**Comment by deepali-c** [comment]
Yes, it worked.

**Comment by hma02** [comment]
okay closed
