### ISSUE TITLE
latest update to conda and I started getting this issue:  TypeError: slice indices must be integers or None or have an __index__ method

### ISSUE THREAD

**Issue by Magotraa** [uoguelph-mlrg/theano_alexnet#37]
I was able to execute the code on theano0.9.0 on windows and then I update the latest conda package: conda update --all and this issue.. 

... training
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\arjun\Anaconda2\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Users\arjun\Anaconda2\lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Rough\random\xxx\xxxxxyyyyyy\xx\yy\xxxxxyyyy\train.py", line 127, in train_net
    recv_queue=load_recv_queue)
  File "D:\Rough\random\xxx\xxxxxyyyyyy\xx\yy\xxxxxyyyy\train_funcs.py", line 166, in train_model_wrap
    batch_img = crop_and_mirror(batch_img, param_rand, flag_batch=flag_batch)
  File "D:\Rough\random\xxx\xxxxxyyyyyy\xx\yy\xxxxxyyyy\proc_load.py", line 75, in crop_and_mirror
    crop_ys:crop_ys + cropsize]
TypeError: slice indices must be integers or None or have an __index__ method
-------------------------------------------------------------------

**Comment by hma02** [comment]
@aryanbhardwaj 

Which Theano backend are you using?

Maybe you want to try the [pygpu branch](https://github.com/uoguelph-mlrg/theano_alexnet/tree/pygpu) to use the new Theano backend.

There are some [commits](https://github.com/uoguelph-mlrg/theano_alexnet/commit/5eba9808ec13820fe7a917b869c8050a32950b82#diff-07373eb9d5c32041ce70704f1e321cb8R21) addressing this int conversion in that branch.

**Comment by Magotraa** [comment]
@hma02 
Thank you for the quick reply, I am using "Theano 0.9.0 ".
